name: demo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13.3
  - ipykernel
  - pip
  - pip:
    - matplotlib==3.10.3
    - pyscf==2.9.0
    - pyscf_forge==1.0.3
    - qiskit==1.1.1
    - qiskit-algorithms==0.3.1
    - qiskit-nature==0.7.2
    - qiskit_utils==1.2.1
    - scipy==1.15.3